# frontend/Dockerfile

FROM node:20-alpine as builder
WORKDIR /app

COPY package*.json ./
RUN npm install -g @angular/cli@15
RUN npm ci
COPY . .
RUN ng build --output-path=/dist

# Stage 2: Запуск nginx
FROM nginx:alpine

# Меняем конфиг nginx-а на собственный
COPY nginx.conf /etc/nginx/nginx.conf

# Заменяем дефолтную страницу nginx соответствующей веб-приложению
#RUN rm -rf /usr/share/nginx/html/*
# Копируем собранное приложение из предыдущего этапа в рабочую директорию nginx
COPY --from=builder /dist /usr/share/nginx/html
EXPOSE 4200

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]
